config/routes.rb
Ebentum::Application.routes.draw do

  match 'users/search'               => 'users#search'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    match '/users/facebook_login'  => 'users/omniauth_callbacks#facebook_login'
    match '/users/twitter_login'   => 'users/omniauth_callbacks#twitter_login'
    match '/auth_login/callback'   => 'users/omniauth_callbacks#facebook'
    match '/users/edit_password'   => 'users#edit_password'
    match '/users/update_password' => 'users#update_password'
    match '/users/update_position' => 'users#update_position'
    match '/users/update_picture_from_url' => 'users#update_picture_from_url'
  end

  resources :activities

  match '/welcome/sign_up_ok' => 'welcome#sign_up_ok'
  resources :welcome

  match 'events/add_user/:eventid'    => 'events#add_user'
  match 'events/remove_user/:eventid' => 'events#remove_user'
  match 'events/search'               => 'events#search'
  match 'events/event_search'         => 'events#event_search'

  resources :tokens
  match '/social/share_event_appoint' => 'social#share_event_appoint'
  match '/social/get_social_data'     => 'social#get_social_data'
  resources :social
  resources :comments
  resources :pictures
  resources :user_pictures
  resources :event_pictures

  resources :users do
    member do
      get :following, :followers, :event_appointments
      put :follow, :unfollow
    end
  end

  match '/admin/update_fulltext_index'     => 'admin#update_fulltext_index'

  resources :events, except: [:show, :update]

  match '/:id' => 'events#update', :as => 'event', :via => :PUT
  match '/:id' => 'events#show', :as => 'event'

  root :to => 'activities#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  skip_before_filter :auth_user
  before_filter :user_logged, :only => [:index]

  def index
    # para activar el contenido 'especial' para los crawlers
    if isCrawler
      @isCrawler = true
    end
  end

  def sign_up_ok
    @sign_up_email = params[:email]
  end

end

app/views/welcome/_like-button-mobile.html.haml
.fb-like{"data-href" => "http://www.ebentum.com", "data-show-faces" => "false", "data-layout" => "button_count"}

app/views/welcome/_like-button.html.haml
.fb-like{"data-href" => "http://www.ebentum.com", "data-show-faces" => "false", "data-width" => "400"}

app/views/welcome/_login-button-mobile.html.haml
%fb:login-button{"max-rows" => "2", "show-faces" => "true", "registration-url" => "/users/auth/facebook", :size => 'large'}

app/views/welcome/_login-button.html.haml
%fb:login-button{"max-rows" => "1", "show-faces" => "true", :width => '400', "registration-url" => "/users/auth/facebook"}

app/views/welcome/_remember_me.html.haml
= f.label :remember_me, :class => 'checkbox' do
  = f.check_box :remember_me, {style: 'width: 0px;', "data-toggle" => "checkbox", :checked => true}, "1", "0"
  = t('.remember_me')

app/views/welcome/_sign_in_form.html.haml
= form_for(@user, :as => :user, :url => '/users/sign_in', :html => {:method => :post}) do |f|
  .card-header
    = t('.sign_in_welcome')
  .card-content
    .row.visible-xs.visible-sm.mbm
      .col-xs-12.centered
        = render 'sign_in_with'
    .row.hidden-xs.hidden-sm.mbm
      .col-xs-12.centered
        = render 'sign_in_with'
    .row.mbm
      .col-xs-12
        = f.email_field :email, :placeholder => t('.email'), :class => 'form-control input-sm'
    .row.mbs
      .col-xs-12
        = f.password_field :password, :placeholder => t('.password'), :class => 'form-control input-sm'
    .row.hidden-xs.hidden-sm.mbs
      .col-xs-12
        .pull-left
          = render 'remember_me', f: f
    .row.hidden-xs.hidden-sm.mbs
      .col-xs-12
        .pull-left
          %small
            = link_to t('.forgot_your_password'), new_password_path(:user)
    .row.visible-xs.visible-sm
      .col-xs-12
        .pull-left
          = render 'remember_me', f: f
    .row.visible-xs.visible-sm.mbm
      .col-xs-12
        = link_to t('.forgot_your_password'), new_password_path(:user)

  .row.card-footer
    .col-xs-5.col-sm-offset-7.footer-option.option-active.pull-right.btn-round-bottom-right
      .option-action.btn-round-bottom-right
        %button.user_action_button{:type => "submit", :class => "btn btn-primary"}
          = t('.sign_in_button')

app/views/welcome/_sign_in_with.html.haml
.row
  .col-xs-12
    %a.btn.btn-block.btn-social.btn-lg.btn-facebook{:href => '/users/facebook_login'}
      %i.fa.fa-facebook
      = t('.sign_in_with')+" Facebook"
.row
  .col-xs-12
    %a.btn.btn-block.btn-social.btn-lg.btn-twitter{:href => '/users/twitter_login'}
      %i.fa.fa-twitter
      = t('.sign_in_with')+" Twitter"

app/views/welcome/_sign_up_alert.html.haml
.alert.alert-success
  %h4
    = t('.sign_up_ok_title')
  %span
    = t('.sign_up_ok_text', :email => @sign_up_email)

app/views/welcome/_sign_up_form.html.haml
= form_for(@user, :as => :user, :url => '/users', :html => {:method => :post, :id => "welcome_sign_up_form"}) do |f|
  .card-header
    = t('.new_sign_up')
  .card-content
    .row.visible-xs.visible-sm.mbm
      .col-xs-12.centered
        = render 'sign_up_with'
    .row.hidden-xs.hidden-sm.mbm
      .col-xs-12.centered
        = render 'sign_up_with'
    = f.hidden_field :user_confirmation_required, :value => 'true'
    .row.mbm
      .col-xs-12
        = f.text_field :complete_name, :placeholder => t('.complete_name'), :class => 'form-control input-sm'
    .row.mbm
      .col-xs-12
        = f.email_field :email, :placeholder => t('.email'), :class => 'form-control input-sm'
    .row.mbm
      .col-xs-12
        = f.password_field :password, :placeholder => t('.password'), :class => 'form-control input-sm'
    .row.mbm
      .col-xs-12
        = f.password_field :password_confirmation, :placeholder => t('.password_confirmation'), :class => 'form-control input-sm'
  .row.card-footer
    .col-xs-5.col-sm-offset-7.footer-option.option-active.pull-right.btn-round-bottom-right
      .option-action
        %button#welcome_sign_up_button{:type => "submit", :class => "btn btn-primary", :data => {'loading-text' => t('.signing_up')}}
          = t('.sign_up_button')

app/views/welcome/_sign_up_with.html.haml
.row
  .col-xs-12
    %a.btn.btn-block.btn-social.btn-lg.btn-facebook{:href => '/users/auth/facebook'}
      %i.fa.fa-facebook
      = t('.sign_up_with')+" Facebook"
.row
  .col-xs-12
    %a.btn.btn-block.btn-social.btn-lg.btn-twitter{:href => '/users/auth/twitter'}
      %i.fa.fa-twitter
      = t('.sign_up_with')+" Twitter"

app/views/welcome/index.html.haml
.col-xs-8.hidden-xs.hidden-sm
  .row
    .card.welcome-title
      .card-content
        .row
          %h1
            = t('.discover_share')
        .row.welcome-title-footer
          .col-xs-8
            .fb-login-button
              = render 'login-button'
          .col-xs-4
            .pull-right.welcome-gplay-link
              %a{:href => "https://play.google.com/store/apps/details?id=com.ebentum.ebentumapp"}
                %img{:alt => "Get it on Google Play", :src => "/images/es_generic_rgb_wo_45.png"}

.col-xs-4.hidden-xs.hidden-sm
  .row
    .col-xs-12
      .card
        = render 'sign_in_form'
  .row
    .col-xs-12
      .card
        = render 'sign_up_form'
.col-xs-12.visible-xs.visible-sm
  .row
    .col-xs-12
      .card
        = render 'sign_in_form'
  .row
    .col-xs-12
      .card
        = render 'sign_up_form'
.col-xs-12.visible-xs.visible-sm
  .row
    .col-xs-12
      .card
        .card-content
          = render 'login-button-mobile'

app/views/welcome/sign_up_ok.html.haml
.col-xs-2
.col-xs-7
  .row
    .col-xs-12
      = render 'sign_up_alert'
.col-xs-3