config/routes.rb
Ebentum::Application.routes.draw do

  match 'users/search'               => 'users#search'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    match '/users/facebook_login'  => 'users/omniauth_callbacks#facebook_login'
    match '/users/twitter_login'   => 'users/omniauth_callbacks#twitter_login'
    match '/auth_login/callback'   => 'users/omniauth_callbacks#facebook'
    match '/users/edit_password'   => 'users#edit_password'
    match '/users/update_password' => 'users#update_password'
    match '/users/update_position' => 'users#update_position'
    match '/users/update_picture_from_url' => 'users#update_picture_from_url'
  end

  resources :activities

  match '/welcome/sign_up_ok' => 'welcome#sign_up_ok'
  resources :welcome

  match 'events/add_user/:eventid'    => 'events#add_user'
  match 'events/remove_user/:eventid' => 'events#remove_user'
  match 'events/search'               => 'events#search'
  match 'events/event_search'         => 'events#event_search'

  resources :tokens
  match '/social/share_event_appoint' => 'social#share_event_appoint'
  match '/social/get_social_data'     => 'social#get_social_data'
  resources :social
  resources :comments
  resources :pictures
  resources :user_pictures
  resources :event_pictures

  resources :users do
    member do
      get :following, :followers, :event_appointments
      put :follow, :unfollow
    end
  end

  match '/admin/update_fulltext_index'     => 'admin#update_fulltext_index'

  resources :events, except: [:show, :update]

  match '/:id' => 'events#update', :as => 'event', :via => :PUT
  match '/:id' => 'events#show', :as => 'event'

  root :to => 'activities#index'

end

app/models/event.rb
class Event
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip
  include Paperclip::Glue
  include Geocoder::Model::Mongoid
  include Mongoid::Slug
  include Mixins::Search #TODO Cuando salga mongoid 4.0 esto habrá que sustituirlo

  slug do |cur_object|
    "#{cur_object.name}".parameterize
  end

  #Comentados ya que fallan al crearse en la bd de producción proque es experimental. Descomentar en el futuro.
  #index({ start_date: 1, name: "text", appointments_count: -1 })
  #index({ start_date: 1, coordinates: "2d", appointments_count: -1 })


  field :name, type: String
  field :description, type: String
  field :place, type: String
  field :active, type: Boolean
  field :start_date, type: DateTime
  field :coordinates, type: Array
  field :lat, type: BigDecimal
  field :lng, type: BigDecimal
  field :appointments_count, type: Integer, default: 0

  reverse_geocoded_by :coordinates

  attr_accessible :active, :description, :name, :place, :start_date, :lat, :lng #:photo
  validates :name, :place, :start_date, :lat, :lng, presence: true

  belongs_to :creator, class_name: "User", inverse_of: :created_events
  has_one :main_picture, class_name: "EventPicture", as: :pictureable, dependent: :destroy
  has_and_belongs_to_many :users, inverse_of: :events
  has_many :comments, inverse_of: :event, dependent: :destroy


  def setCoordinates
    self.coordinates = [self.lng.to_f, self.lat.to_f]
    self.save
  end

  def calculate_appointments
    self.appointments_count = self.users.size
    self.save
  end

  def get_picture
    if self.main_picture?
      self.main_picture
    else
      EventPicture.new
    end
  end

  after_create do |event|
    receivers = self.creator.all_followers.map {|user| user.id}
    receivers << self.creator.id

    Activity.new(
      :verb => "create",
      :actor_id => self.creator.id,
      :object_type => "Event",
      :object_id => self.id,
      :receivers => receivers,
      :date => Time.now
    ).save

  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  skip_before_filter :auth_user, :only => [:show]
  before_filter :search_events, :only => [:index]

  def search_events
    if params[:user_id]
      @user = User.find(params[:user_id])
    end

    if @user
      if params[:appointments]
        @events = @user.events
      else
        @events = @user.created_events
      end
    end

  end

  def event_search

  end

  def search
    # para activar el contenido 'especial' para los crawlers
    if isCrawler
      @isCrawler = true
    end

    @page = params[:page] || 1

    # ojo si somos un crawler
    if isCrawler
      my_location = [43.31833, -1.98123] # San sebastian, ojo ahí
    else
      user = current_user
      my_location = [user.coordinates[1], user.coordinates[0]]
    end

    @daysSelected     = params[:days]     || 30 # Un mes
    @text             = params[:text]
    if @text.nil? || @text == ""
      @distanceSelected = params[:distance] || 50 # 50 kilometros
    end
    @events           = Event

    if !@distanceSelected.nil? && @distanceSelected.to_i > 0
      @events = @events.near(my_location, @distanceSelected, :units => :km)
    end

    if !@daysSelected.nil? && @daysSelected.to_i > 0
      @events = @events.where(:start_date.gte => Date.today, :start_date.lte => @daysSelected.to_i.days.from_now)
    end

    @events = @events.order_by("appointments_count desc")
    @events = @events.page(@page)

    if !@text.nil? && @text != ""
      @events = TextSearch.new(Mongoid.session('default')[:events], @events, @text)
    end

    if request.xhr?
      js_callback false
    end

    respond_to do |format|
      if request.xhr?
        format.html { render :layout => nil}
      else
        format.html { render :layout => 'fullwidth' }
      end
      format.json { render json: @events }
    end
  end

  def index
    @page = params[:page] || 1

    @events = @events.order_by("start_date desc")
    @events = @events.page(@page)

    if request.xhr?
      js_callback false
    end

    respond_to do |format|
      if request.xhr?
        format.html { render :layout => nil}
      else
        format.html { render :layout => 'fullwidth' }
      end
      format.json { render json: @events }
    end
  end


  def show

    # tiene token de acceso validos?
    if current_user
      @fb_access_token = current_user.fbtoken || nil
      @tw_access_token = current_user.twtoken || nil
    end

    @event = Event.find(params[:id])
    if user_signed_in?
      @joined = @event.users.find(current_user) != nil
      # en caso de => raise_not_found_error: true
      # begin
      #   @joined = @event.users.find(current_user) != nil
      # rescue Mongoid::Errors::DocumentNotFound
      #   @joined = false
      # end
    end
    @event_users = @event.users.size

    @event_comments = @event.comments.size

    # Temas de mejora de SEO
    @head_title       = @event.name
    @meta_description = @event.description+' '+t(:meta_description, :event_name => @event.name, :joined => @event_users)
    @meta_keywords    = @event.description

    js_callback :params => {:event_id => @event.id, :lat => @event.lat, :lng => @event.lng, :joined => @joined}

    # open graph
    @og_title       = @event.name
    @og_type        = 'website'
    @og_description = @meta_description
    @og_url         = 'http://www.ebentum.com'+event_path(@event)
    @og_image       = @event.get_picture.photo.url(:medium)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @event }
    end
  end


  def new
    @event = Event.new
    @picture = EventPicture.new

    respond_to do |format|
      if @native_app == false
        format.html { render :layout => 'modal_window' }
      else
        format.html {}
      end
      format.json { render :json => @event }
    end
  end

  def create
    @event = Event.new(params[:event])
    # Meter 'lat' y 'lng' en array 'coordinates'
    @event.coordinates = [params[:event][:lng].to_f, params[:event][:lat].to_f] # to_f para pasarlos a float
    @event.creator = current_user

    picture = EventPicture.find(params[:event][:main_picture_id])
    if picture
      @event.main_picture = picture
      picture.save
    #else
    #  picture = Picture.new
    #  @event.main_picture = picture
    end


    respond_to do |format|
      if @event.save
        format.html  { redirect_to(@event,
                      :notice => 'Event was successfully created.') }
        format.json  { render :json => @event,
                      :status => :created, :location => @event }
      else
        format.html  { render :action => "new" }
        format.json  { render :json => @event.errors,
                      :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @event = Event.find(params[:id])
    @picture = @event.get_picture

    respond_to do |format|
      if @native_app == false
        format.html { render :layout => 'modal_window' }
      else
        format.html {}
      end
      format.json { render :json => @event }
    end
  end

  def update
    @event = Event.find(params[:id])

    if @event.creator != current_user
      render :json => false
    else
      picture = Picture.find(params[:event][:main_picture_id])
      if params[:event][:main_picture_id] != '#'
        if picture.nil?
          @event.main_picture = nil
        else
          @event.main_picture = picture
        end
      end

      respond_to do |format|
        if @event.update_attributes(params[:event])
          format.html  { redirect_to(@event,
                        :notice => 'Event was successfully updated.') }
          format.json  { head :no_content }
        else
          format.html  { render :action => "edit" }
          format.json  { render :json => @event.errors,
                        :status => :unprocessable_entity }
        end
      end
    end
  end

  def destroy
    @event = Event.find(params[:id])

    if @event.creator != current_user
      render :json => false
    else
      @event.destroy

      respond_to do |format|
        format.html { redirect_to events_url }
        format.json { head :no_content }
      end
    end
  end

  def add_user
    event_id = params[:eventid]
    event    = Event.find(event_id)
    event.users.push(current_user)
    event.appointments_count = event.appointments_count + 1
    receivers = current_user.all_followers.map {|user| user.id}
    receivers << current_user.id

    Activity.new(
      :verb => "join",
      :actor_id => current_user.id,
      :object_type => "Event",
      :object_id => event.id,
      :receivers => receivers,
      :date => Time.now
    ).save

    render :json => event.save
  end

  def remove_user
    event_id = params[:eventid]
    event    = Event.find(event_id)
    user     = current_user
    event.users.delete(user)
    event.appointments_count = event.appointments_count - 1

    render :json => event.save
  end

end

app/helpers/events_helper.rb
module EventsHelper

  def og_title(title)
    if title
      title
    else
      'ebentum'
    end
  end

  def og_description(description)
    if description
      description
    else
      t(:meta_description_default)
    end
  end

  def og_type(type)
    if type
      type
    else
      'website'
    end
  end

  def og_url(url)
    if url
      url
    else
      'http://www.ebentum.com'
    end
  end

  def og_image(image)
    if image
      image
    else
      'http://www.ebentum.com/images/logo.png'
    end
  end

end

app/views/events/_appointed_list.html.haml
%ul.media-list.appointed-list{:id => 'event_appoints'}
  - @event_users.each do |user|
    - if current_user != user # si no soy yo
      = render 'appointed_user', :user => user

app/views/events/_appointed_user.html.haml
%li.media.card-content
  %a.pull-left{:href => "#"}
    = image_tag(user.get_picture.photo.url(:thumb), :class => 'block media-object thumb_image')
  .media-body
    %a{:href => user_path(user)}
      = user.complete_name
    .pull-right
      - if !current_user.follower_of?(user)
        %button.btn.btn-success.pull-right(type='button')
          = t('.seguir')

app/views/events/_confirm_appoint.html.haml
.modal.fade{:id  => 'confirm_appoint'}
  .modal-dialog.card
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        = t('.confirm')
      .modal-body
        %p
          = t('.confirm_text')
        = render 'share'
      .card-footer
        %a.btn{:href => "#", "data-dismiss" => "modal"}
          = t('.close')
        %a.btn.btn-primary.btn-round-bottom-right{:href => "#", :id => 'confirm_appoint_btn', :data => {:eventid => @event.id}}
          = t('.confirm')

app/views/events/_confirm_delete_event.html.haml
.modal.fade{:id  => 'confirm_delete_event'}
  .modal-dialog.card
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        = t('.confirm')
      .modal-body
        %p
          = t('.confirm_delete_event_text')
      .card-footer
        %a.btn{:href => "#", "data-dismiss" => "modal"}
          = t('.close')
        %a.btn.btn-primary.btn-round-bottom-right{:href => "#", :id => 'confirm_delete_event_btn', :data => {:eventid => @event.id, :userid => current_user.id}}
          = t('.confirm')

app/views/events/_event_card.html.haml
- pictureInfo = PicturesController.helpers.getPictureData(event.main_picture, 'card', 'event')
- image_url = pictureInfo[0]
- width = pictureInfo[1]
- height = pictureInfo[2]
- creator = User.find(event.creator)

- cardStyles = PicturesController.helpers.getCardStyles(browser.mobile?, image_url, width, height)
- card_style = cardStyles[:card_style]
- card_class = cardStyles[:card_class]
- image_style = cardStyles[:image_style]

.card{:style => card_style, :class => card_class}
  .card-content{:style => "padding: 0;"}
    %a{:href => event_path(event)}
      .card-image-placeholder{:style => image_style}

  .card-content{:style => "background-color: #fff; padding: 0px;"}
    .media
      .pull-right
        .calendar-icon
          .calendar-month
            = event.start_date.strftime("%b")
          .calendar-day
            = event.start_date.strftime("%d")
      .media-body.plm.ptm.pbm.prn
        = event.name
        .sub-paragraph
          = event.place
  .card-footer.card-footer-masonry
    .media
      .pull-left
        .sub-paragraph.plm.ptm
          = t('.created_by')

      .media-body.plm.ptm.pbm.prn
        %a{:href => user_path(creator)}
          = creator.complete_name

app/views/events/_no_results.html.haml
- if @page == 1 && @events.count == 0
  - cardStyles = PicturesController.helpers.getCardStyles(browser.mobile?, "", 230, 300)
  - card_style = cardStyles[:card_style]
  - card_class = cardStyles[:card_class]
  - image_style = cardStyles[:image_style]
  .card{:style => card_style, :class => card_class}
    .card-image-placeholder{:style => "width: 100%; height: 200px;"}
      %a{:href => "/events/event_search"}
        %i.fa.fa-search.card-icon-big
    .card-footer.card-footer-masonry.pts.pbs.plm.prm
      .media
        .media.body.center-text
          = t('.no_data_found')

app/views/events/_pagination.html.haml
- page = @page.to_i
- if page == 1
  - previousPage = 1
- else
  - previousPage = page - 1

- nextPage = page + 1
- text ||= ''
- distanceSelected = @distanceSelected.to_s
- daysSelected = @daysSelected.to_s
- search_url = "search?distance="+distanceSelected+"&text="+text+"&days="+daysSelected
%ul.pagination
  %li
    %a{href: search_url+"&page="+previousPage.to_s}
      = t('.previous')
  %li
    %a{href: search_url+"&page="+nextPage.to_s}
      = t('.next')

app/views/events/_share.html.haml
- if @fb_access_token
  .row
    %label.control-label.col-sm-4
      = t('.share_activity', :provider => 'Facebook')
    .controls.col-sm-8
      .switch
        - fbPubCheched = false
        - if @fb_access_token.autopublish
          - fbPubChecked = true
        %input#facebook_post{:type => "checkbox", :checked => fbPubChecked, "data-toggle" => "switch"}

- if @tw_access_token
  .row
    %label.control-label.col-sm-4
      = t('.share_activity', :provider => 'Twitter')
    .controls.col-sm-8
      .switch
        - twPubCheched = false
        - if @tw_access_token.autopublish
          - twPubCheched = true
        %input#twitter_post{:type => "checkbox", :checked => twPubCheched, "data-toggle" => "switch"}

app/views/events/_share_event.html.haml
- url = 'http://www.ebentum.com'+event_path(@event)
- short_url = Googl.shorten(url).short_url
- eventName = nil
- if @event.name.size > 90
  - eventName = "'"+@event.name.slice(0, 90)+"...'"
- else
  - eventName = "'"+@event.name+"'"

- if @native_app
  #event-short-url.hidden
    = short_url
- else
  .col-xs-6.col-md-3.footer-option
    .option-action{:style => "max-width: 100px;"}
      .fb-like{"data-layout" => "button", "data-send" => "false", "data-show-faces" => "false", "data-width" => "450", "data-href" => url, 'data-share' => 'true'}

  .col-xs-6.col-md-2.footer-option
    .option-action{:style => "max-width: 100px;"}
      %a.twitter-share-button{"data-lang" => "es", :href => "https://twitter.com/share", :data => {:url => short_url, :via => 'ebentumApp', :text => eventName}}

app/views/events/edit.html.haml
- content_for(:modal_header) do
  %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
  = t(".edit_event")

- if @native_app
  .container
    .row
      .col-xs-12
        .card
          = render 'form'
- else
  = render 'form'

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Start datetime</th>
    <th>Place</th>
    <th>User</th>
    <th>Active</th>
    <th>Photo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td><%= event.description %></td>
    <td><%= event.start_datetime %></td>
    <td><%= event.place %></td>
    <td><%= event.user_id %></td>
    <td><%= event.active %></td>
    <td><%= event.photo %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/index.html.haml
- if @page == 1
  .col-xs-12
    #events_list.masonry_layout.centered.invisible
      = render 'list'
- else
  = render 'list'

app/views/events/popular.html.haml
= render 'list'

app/views/events/search.html.haml
- if !request.xhr? # si no es una llamada ajax mostramos el form de busqueda
  .container
    .col-xs-12
      %form.event_search_form#event_search_form
        .card
          .card-content
            .row
              .col-xs-12.col-md-3.mbs.mts
                #filter_type.btn-group
                  = button_tag t('.distance'), id: "by_distance", class: "btn btn-primary active", type: "button"
                  = button_tag t('.name'), id: "by_name", class: "btn btn-primary", type: "button"
              .col-xs-12.col-md-4.mbs.mts
                - distanceOptions  = [t('.close_to_me'), 2], [t('.to_20_km'), 20], [t('.to_50_km'), 50], [t('.i_dont_care'), 0]
                = select_tag 'distance', options_for_select(distanceOptions, @distanceSelected), {:class => "form-control"}
                = text_field_tag :text, @text, class: 'form-control hidden disabled', placeholder: t('.name')
              .col-xs-12.col-md-3.mbs.mts
                - daysOptions  = [t('.soon'), 2], [t('.one_week'), 7], [t('.one_month'), 30], [t('.i_dont_care'), 99999]
                = select_tag 'days', options_for_select(daysOptions, @daysSelected), {:class => "form-control"}
              .col-xs-12.col-md-2.mbs.mts
                - if @isCrawler
                  = submit_tag t('.search'), class: 'btn btn-primary btn-block'
                - else
                  = submit_tag t('.search'), class: 'btn btn-primary btn-block', id: 'search_button'
  .col-xs-12
    #events_list.masonry_layout.centered
      = render 'no_results'
      = render 'list'
  .col-xs-4.col-xs-offset-5
    - if @isCrawler
      = render 'pagination'

- else # es una llamada ajax
  = render 'no_results'
  = render 'list'