config/routes.rb
Ebentum::Application.routes.draw do

  match 'users/search'               => 'users#search'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    match '/users/facebook_login'  => 'users/omniauth_callbacks#facebook_login'
    match '/users/twitter_login'   => 'users/omniauth_callbacks#twitter_login'
    match '/auth_login/callback'   => 'users/omniauth_callbacks#facebook'
    match '/users/edit_password'   => 'users#edit_password'
    match '/users/update_password' => 'users#update_password'
    match '/users/update_position' => 'users#update_position'
    match '/users/update_picture_from_url' => 'users#update_picture_from_url'
  end

  resources :activities

  match '/welcome/sign_up_ok' => 'welcome#sign_up_ok'
  resources :welcome

  match 'events/add_user/:eventid'    => 'events#add_user'
  match 'events/remove_user/:eventid' => 'events#remove_user'
  match 'events/search'               => 'events#search'
  match 'events/event_search'         => 'events#event_search'

  resources :tokens
  match '/social/share_event_appoint' => 'social#share_event_appoint'
  match '/social/get_social_data'     => 'social#get_social_data'
  resources :social
  resources :comments
  resources :pictures
  resources :user_pictures
  resources :event_pictures

  resources :users do
    member do
      get :following, :followers, :event_appointments
      put :follow, :unfollow
    end
  end

  match '/admin/update_fulltext_index'     => 'admin#update_fulltext_index'

  resources :events, except: [:show, :update]

  match '/:id' => 'events#update', :as => 'event', :via => :PUT
  match '/:id' => 'events#show', :as => 'event'

  root :to => 'activities#index'

end

app/models/activity.rb
class Activity < CouchRest::Model::Base
  use_database 'activities'

  property :verb, String
  property :actor_id, String
  property :object_type, String
  property :object_id, String
  property :receivers, [String]
  property :date, Time

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def index
    @last_activity_date = params[:last_activity_date]
    @activities = ActivityStream.user_activity_stream(current_user, @last_activity_date)

    if request.xhr?
      js_callback false
    end

    @show_fb_friends = params[:show_fb_friends]

    if !current_user.fbtoken.nil?
      @fb_friends = get_token_friends_with_ebentum(current_user.fbtoken.token)
    end

    respond_to do |format|
      if request.xhr?
        format.html { render :layout => nil}
      else
        format.html { render :layout => 'fullwidth' }
      end
      format.json { render json: @activities }
    end
  end

  # TODO: Refactor, en el modelo fbtoken tenemos el mismo código.
  # funcion que devuelve un array de ids de usuario de ebentum que son amigos nuestros en facebook
  def get_token_friends_with_ebentum(token)
    # array de ids de ususario de ebentum a los que hay que notificar
    friends = []
    # instanciamos el objeto fb
    fb = Koala::Facebook::API.new(token)
    # uids de fb de nuestros amigos de fb que tienen ebentum
    fb_uids = fb.get_connections("me", "friends", :fields => "id, installed") # amigos de fb. obtenemos id e installed (ebentum)
              .select {|user| user.key?('installed')} # nos quedamos con los que tienen ebentum instalado
              .map {|installed| installed['id']} # de los que tienen ebentum instalado nos quedamos con la id de fb
    # obtenemos los usuarios de ebentum que tienen esas uids de en el token de fb
    users = User.in('fbtoken.uid' => fb_uids)
    if users.count > 0
      users.each do |user|
        friends.push user#.id Aqui tenemos que pasar el user entero
      end
    end
    logger.info('fb friends with ebentum')
    logger.info(friends)
    return friends
  end

end

app/views/activities/_activity_card.html.haml
- if !activity[:event].nil?
  - object_type = :event
  - picture = EventPicture.new
  - object_path = event_path(activity[:event])
  - object_name = activity[:event].name
- elsif !activity[:user].nil?
  - object_type = :user
  - picture = UserPicture.new
  - object_path = user_path(activity[:user])
  - object_name = activity[:user].complete_name
  - object_id = activity[:user].id

- if !activity[object_type].main_picture.nil?
  - picture = activity[object_type].main_picture
  - cardSize = PicturesController.helpers.adjustCardSize(picture.photo_dimensions["card"][0], picture.photo_dimensions["card"][1])
- else
  - cardSize = PicturesController.helpers.adjustCardSize(nil, nil)


- width = cardSize[:width]
- height = cardSize[:height]
- image_url = picture.photo.url(:card)

- cardStyles = PicturesController.helpers.getCardStyles(browser.mobile?, image_url, width, height)
- card_style = cardStyles[:card_style]
- card_class = cardStyles[:card_class]
- image_style = cardStyles[:image_style]


.card{:style => card_style, :class => card_class, :data => {:activity_date => activity[:date]}}
  .card-content{:style => "padding: 0;"}
    %a{:href => object_path}
      .card-image-placeholder{:style => image_style}
  .card-content.pts.pbs.plm.prm{:style => "background-color: #fff"}
    %div
      = object_name

  - activity[:actions].each do |action|
    - if !action[:receiver].nil?
      - if !action[:receiver].main_picture.nil?
        - user_picture = action[:receiver].main_picture
        - if user_picture.nil?
          - user_picture = UserPicture.new
      - else
        - user_picture = UserPicture.new

      .card-footer.card-footer-masonry.pts.pbs.plm.prm
        .media
          - if action[:verb] == 'fbregister'
            .media.body
              %div
                = t('.' + action[:verb])
              .sub-paragraph
                .format-timeago{:data => {:datevalue => action[:date]}}
              = render 'add_to_friends', {:user_id => object_id, :user => nil}
          - else
            .pull-left
              %a{:href => user_path(action[:receiver])}
                = image_tag(user_picture.photo.url , :class => 'block media-object thumb_image')
            .media.body
              %div
                = action[:receiver].complete_name
              .sub-paragraph
                = t('.' + action[:verb], :display_name => object_name)
              .sub-paragraph
                .format-timeago{:data => {:datevalue => action[:date]}}

app/views/activities/_add_to_friends.html.haml
- user = user || User.find(user_id)
- if current_user != user # si somos nosotros no podemos seguirnos, claro
  - if !current_user.follower_of?(user)
    %a{:href => '#'}
      %div.centered_text.follow-activity{:data => {:user_id => user.id}}
        %br
        %i.fa.fa-plus
        %i.fa.fa-user.fa-2x
        = t('.add_to_friends')

app/views/activities/_list.html.haml
- for activity in @activities
  - if !activity[:event].nil? || !activity[:user].nil?
    = render partial: 'activity_card', locals: {activity: activity}

app/views/activities/index.html.haml
- if @last_activity_date.nil?
  .col-xs-12
    #activity_list.masonry_layout.centered.invisible
      - if @activities.count == 0
        - cardStyles = PicturesController.helpers.getCardStyles(browser.mobile?, "", 230, 300)
        - card_style = cardStyles[:card_style]
        - card_class = cardStyles[:card_class]
        - image_style = cardStyles[:image_style]
        .card{:style => card_style, :class => card_class}
          .card-image-placeholder{:style => "width: 100%; height: 200px;"}
            %a{:href => "/events/event_search"}
              %i.fa.fa-compass.card-icon-big
          .card-footer.card-footer-masonry.pts.pbs.plm.prm
            .media
              .media.body.center-text
                = t('.no_activities1')
              .media.body.center-text
                = t('.no_activities2')
      - else
        = render 'list'
- else
  = render 'list'

- if @show_fb_friends && @fb_friends.size > 0
  .modal.fade{:id  => 'show_fb_friends'}
    .modal-dialog.card
      .modal-content
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
          = t('.add_fb_friends')
        .modal-body
          %ul.media-list.comment-list
            - for fb_friend in @fb_friends
              - if !current_user.follower_of?(fb_friend)
                %li.media.card-content
                  %a.pull-left{:href => user_path(fb_friend)}
                    = image_tag(fb_friend.get_picture.photo.url(:thumb), :class => 'block media-object thumb_image')
                  .media-body
                    %a{:href => user_path(fb_friend)}
                      = fb_friend.complete_name
                    .pull-right
                      = render 'activities/add_to_friends', {:user_id => nil, :user => fb_friend}
        .card-footer
          %a.btn.btn-primary.btn-round-bottom-right{:href => "#", "data-dismiss" => "modal"}
            = t('.done')